###
GET http://localhost:9999/hello?id=99
Accept: application/json

###
GET http://127.0.0.1:9999/demo?name=1235_b
Accept: application/json

###
GET http://127.0.0.1:9999/test500
Accept: application/json

###
GET http://127.0.0.1:9999/find/100
Accept: application/json

###
POST http://127.0.0.1:9999/submit
Content-Type: application/json

{
  "name": "lsm",
  "age": 40
}