###
GET http://localhost:8080/hello?id=99
Accept: application/json

###
GET http://127.0.0.1:8080/demo?name=1235_b
Accept: application/json

###
GET http://127.0.0.1:8080/test500
Accept: application/json

###
GET http://127.0.0.1:8080/find/100
Accept: application/json

###
POST http://127.0.0.1:8080/submit
Content-Type: application/json

{
  "name": "lsm",
  "age": 40
}